### PR TITLE
Cran check

### PR DESCRIPTION
**Pull request by olivroy**
Hi @richelbilderbeek,

With this Pull Request I'd would like to help reduce dependencies.

Sure, I've read [CONTRIBUTING.md](https://github.com/ropensci/beautier/blob/master/CONTRIBUTING.md) :+1:

Cheers, Olivier

## Details

* You have to be careful. Currently, testthat is used unconditionally in R code. However, there are lighter dependencies such as rlang and its standalone file for type-checking. I have used a similar strategy as ropensci/beautier#140.

* You import devtools in your package for `session_info()`. However, as devtools is a metapackage like the tidyverse, it is possible to only import the sessioninfo package. I recommend this read https://www.tidyverse.org/blog/2018/10/devtools-2-0-0/#conscious-uncoupling

However, for some reason, I cannot get rJava to work on my machine. Therefore, was not able to test what I did. 

So you may have to fix some regexp for `expect_error()` in tests. also needs `devtools::document()`

* I replaced usage of testit::assert by testthat::expect_true in tests, and by check_true in R code.

This PR is not as thorough and good as the one I made for the beautier package. But I thought I'd show you some more tricks 

Happy to answer questions.

EDIT: Needs **devtools::document()** to update NAMESPACE as well.

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
Hi @olivroy, 

I will happily except your work when all tests pass! Also, I will add you to the CONTRIBUTORS too then :-) . And great you picked up to work on `develop`!

**Comment by olivroy** [comment]
I tried to work around it. Hopefully, it will work.

**Comment by olivroy** [comment]
@richelbilderbeek I got R CMD CHECK to pass. I will send a small fix to beautier soon to avoid using testthat in R/ as users may not have that dependency installed. (it is suggests)

**Comment by richelbilderbeek** [comment]
Awesome, thanks so much @oliveroy!

**Pull request merged**
